let premp3 = [
    '#EXTINF:208,Carlo Serafini - 7edo dance',
    '7edo dance',
    '#EXTINF:254,Carlo Serafini - 10 PRS',
    '10 PRS',
    '#EXTINF:261,Carlo Serafini - 11 Dwarfs',
    '11 Dwarfs',
    '#EXTINF:321,Carlo Serafini - 13 Miles',
    '13 Miles',
    '#EXTINF:194,Carlo Serafini - 23 Laments',
    '23 Laments',
    '#EXTINF:324,Carlo Serafini -  50 Shades Of Gamma',
    '50 Shades Of Gamma',
    '#EXTINF:130,Carlo Serafini - 88Bulgarians',
    '88Bulgarians',
    '#EXTINF:259,Carlo Serafini - 88east',
    '88east',
    '#EXTINF:149,Carlo Serafini - 88vocoeast',
    '88vocoeast',
    '#EXTINF:195,Carlo Serafini - AdagioGamma',
    'AdagioGamma',
    '#EXTINF:192,Carlo Serafini - Alfred',
    'Alfred',
    '#EXTINF:168,Carlo Serafini - AlgoXenoJazz',
    'AlgoXenoJazz',
    '#EXTINF:295,Carlo Serafini - Alpha Abstract 1',
    'Alpha Abstract 1',
    '#EXTINF:48,Carlo Serafini - AlphaBlues',
    'AlphaBlues',
    '#EXTINF:106,Carlo Serafini - Alpha Choir',
    'Alpha Choir',
    '#EXTINF:213,Carlo Serafini - Alpha Delinquent',
    'Alpha Delinquent',
    '#EXTINF:210,Carlo Serafini - Alphadesert',
    'Alphadesert',
    '#EXTINF:192,Carlo Serafini - AlphaDulcimer',
    'AlphaDulcimer',
    '#EXTINF:213,Carlo Serafini - Alpha El Din',
    'Alpha El Din',
    '#EXTINF:266,Carlo Serafini -  Alphanon',
    'Alphanon',
    '#EXTINF:165,Carlo Serafini - AlphaTherem Waltz',
    'AlphaTherem Waltz',
    '#EXTINF:395,Carlo Serafini -  Ananda Dance',
    'Ananda Dance',
    '#EXTINF:247,Carlo Serafini - A Nearly Normal Sunday (384ED2)',
    'A Nearly Normal Sunday (384ED2)',
    '#EXTINF:162,Carlo Serafini - An Irishman In Guangdong',
    'An Irishman In Guangdong',
    '#EXTINF:532,Carlo Serafini - Around The Bonfire',
    'Around The Bonfire',
    '#EXTINF:90,Carlo Serafini - Alpha Seems To be The Hardest World',
    'Alpha Seems To be The Hardest World',
    '#EXTINF:476,Carlo Serafini - Atlantis',
    'Atlantis',
    '#EXTINF:294,Carlo Serafini - Autumnal Modulations',
    'Autumnal Modulations',
    '#EXTINF:319,Carlo Serafini -  Babylon Gamma',
    'Babylon Gamma',
    '#EXTINF:257,Carlo Serafini - Berimbau 13',
    'Berimbau 13',
    '#EXTINF:238,Carlo Serafini - Bhairava bungalow',
    'Bhairava bungalow',
    '#EXTINF:264,Carlo Serafini - Bicycles And Bowls',
    'Bicycles And Bowls',
    '#EXTINF:96,Carlo Serafini - Bix In The Sky with Gamma',
    'Bix In The Sky with Gamma',
    '#EXTINF:242,Carlo Serafini - Blues10',
    'Blues10',
    '#EXTINF:168,Carlo Serafini - Bohl-en roll',
    'Bohl-en roll',
    '#EXTINF:248,Carlo Serafini - Bossa Sbilenca',
    'Bossa Sbilenca',
    '#EXTINF:75,Carlo Serafini - CarlosGlass1',
    'CarlosGlass1',
    '#EXTINF:198,Carlo Serafini - Chameleons in the dark',
    'Chameleons in the dark',
    '#EXTINF:315,Carlo Serafini - Chameleons In The Sun',
    'Chameleons In The Sun',
    '#EXTINF:77,Carlo Serafini - Close encounters of the nth kind',
    'Close encounters of the nth kind',
    '#EXTINF:239,Carlo Serafini - Concertina 13',
    'Concertina 13',
    '#EXTINF:264,Carlo Serafini - Conference Of Flutes',
    'Conference Of Flutes',
    '#EXTINF:234,Carlo Serafini - Cubana Al Cubana Pha',
    'Cubana Al Cubana Pha',
    '#EXTINF:113,Carlo Serafini - Dawn Of Beta',
    'Dawn Of Beta',
    '#EXTINF:148,Carlo Serafini - DeltaGammaBlues',
    'DeltaGammaBlues',
    '#EXTINF:148,Carlo Serafini - DeltaGammaBlues2',
    'DeltaGammaBlues2',
    '#EXTINF:211,Carlo Serafini - Desert Winds in 23EDO',
    'Desert Winds in 23EDO',
    '#EXTINF:330,Carlo Serafini - Do Androids Dream Of 18ed2?',
    'Do Androids Dream Of 18ed2',
    '#EXTINF:344,Carlo Serafini - Doomsday 23',
    'Doomsday 23',
    '#EXTINF:131,Carlo Serafini - DorianSchlesinger',
    'DorianSchlesinger',
    '#EXTINF:184,Carlo Serafini - Fast And Furious 13',
    'Fast And Furious 13',
    '#EXTINF:201,Carlo Serafini - Forward Gamma March',
    'Forward Gamma March',
    '#EXTINF:337,Carlo Serafini - From The Diary Of The 13th Fly',
    'From The Diary Of The 13th Fly',
    '#EXTINF:245,Carlo Serafini - FunkEight 1',
    'FunkEight 1',
    '#EXTINF:242,Carlo Serafini - Fuzzy Logic',
    'Fuzzy Logic',
    '#EXTINF:112,Carlo Serafini - Gadudyne',
    'Gadudyne',
    '#EXTINF:217,Carlo Serafini - Galactic Overload',
    'Galactic Overload',
    '#EXTINF:124,Carlo Serafini - gamelanX',
    'gamelanX',
    '#EXTINF:296,Carlo Serafini - Gamma Breezin\'',
    'Gamma Breezin\'',
    '#EXTINF:299,Carlo Serafini - Gamma Constant Structures',
    'Gamma Constant Structures',
    '#EXTINF:256,Carlo Serafini - GammaElegy',
    'GammaElegy',
    '#EXTINF:171,Carlo Serafini - Gammalan',
    'Gammalan',
    '#EXTINF:340,Carlo Serafini - Gamma Meditation',
    'Gamma Meditation',
    '#EXTINF:147,Carlo Serafini - Gamma Monk',
    'Gamma Monk',
    '#EXTINF:192,Carlo Serafini - Gamma Raga',
    'Gamma Raga',
    '#EXTINF:59,Carlo Serafini - Glorious 60',
    'Glorious 60',
    '#EXTINF:86,Carlo Serafini - Glorious Guitars',
    'Glorious Guitars',
    '#EXTINF:64,Carlo Serafini - Groovoland',
    'Groovoland',
    '#EXTINF:267,Carlo Serafini -  Hal Dreams Symphony',
    'Hal Dreams Symphony',
    '#EXTINF:176,Carlo Serafini - Hal Trumpetti',
    'Hal Trumpetti',
    '#EXTINF:182,Carlo Serafini - Hijaz the Charmer',
    'Hijaz the Charmer',
    '#EXTINF:305,Carlo Serafini - Hocus-Bogus 13',
    'Hocus-Bogus 13',
    '#EXTINF:317,Carlo Serafini - In Memoriam JY',
    'In Memoriam JY',
    '#EXTINF:306,Carlo Serafini - In Q',
    'In Q',
    '#EXTINF:56,Carlo Serafini - instant gamelan',
    'instant gamelan',
    '#EXTINF:455,Carlo Serafini - J.F.Sebastian\'s Lullaby',
    'J.F.Sebastian\'s Lullaby',
    '#EXTINF:288,Carlo Serafini - Jayni\'s song',
    'Jayni\'s song',
    '#EXTINF:291,Carlo Serafini - JYs Infra-Worlds',
    'JYs Infra-Worlds',
    '#EXTINF:195,Carlo Serafini - Ligon_Sunday_Sevens',
    'Ligon_Sunday_Sevens',
    '#EXTINF:621,Carlo Serafini - Lotus 13',
    'Lotus 13',
    '#EXTINF:224,Carlo Serafini - Maqam Bayati (JI)',
    'Maqam Bayati (JI)',
    '#EXTINF:64,Carlo Serafini - MetaJar',
    'MetaJar',
    '#EXTINF:216,Carlo Serafini - metashakti',
    'metashakti',
    '#EXTINF:352,Carlo Serafini - Miles Of Space',
    'Miles Of Space',
    '#EXTINF:312,Carlo Serafini - moonsuite',
    'moonsuite',
    '#EXTINF:274,Carlo Serafini - MP13',
    'MP13',
    '#EXTINF:313,Carlo Serafini - nemovar',
    'nemovar',
    '#EXTINF:186,Carlo Serafini - Neutral Steel',
    'Neutral Steel',
    '#EXTINF:294,Carlo Serafini - New World',
    'New World',
    '#EXTINF:272,Carlo Serafini - Nonoctave Melancholic',
    'Nonoctave Melancholic',
    '#EXTINF:384,Carlo Serafini - Nubian Dance',
    'Nubian Dance',
    '#EXTINF:110,Carlo Serafini - Organum 1',
    'Organum 1',
    '#EXTINF:212,Carlo Serafini - Organum 2',
    'Organum 2',
    '#EXTINF:275,Carlo Serafini - OtherWordly 1',
    'OtherWordly 1',
    '#EXTINF:678,Carlo Serafini - Peaceful Soundscape 1',
    'Peaceful Soundscape 1',
    '#EXTINF:153,Carlo Serafini -  Peter Gunn 13',
    'Peter Gunn 13',
    '#EXTINF:178,Carlo Serafini - piano11',
    'piano11',
    '#EXTINF:154,Carlo Serafini - Qablitum',
    'Qablitum',
    '#EXTINF:248,Carlo Serafini - Quarantine 1',
    'Quarantine 1',
    '#EXTINF:230,Carlo Serafini - Quarantine 2',
    'Quarantine 2',
    '#EXTINF:299,Carlo Serafini -  RainForest',
    'RainForest',
    '#EXTINF:216,Carlo Serafini - RibboMan And The Maniacs',
    'RibboMan And The Maniacs',
    '#EXTINF:136,Carlo Serafini - repetitions1',
    'repetitions1',
    '#EXTINF:216,Carlo Serafini - RibboMan And The Maniacs',
    'RibboManAndTheManiacs',
    '#EXTINF:142,Carlo Serafini - ribbonflute',
    'ribbonflute',
    '#EXTINF:327,Carlo Serafini - Sahara',
    'Sahara',
    '#EXTINF:190,Carlo Serafini - SazDul 13',
    'SazDul 13',
    '#EXTINF:250,Carlo Serafini - Sea of Tranquility',
    'Sea of Tranquility',
    '#EXTINF:284,Carlo Serafini - Septimal Klezmer',
    'Septimal Klezmer',
    '#EXTINF:233,Carlo Serafini - Septimal Heaven 2',
    'Septimal Heaven 2',
    '#EXTINF:259,Carlo Serafini - Smooth 10',
    'Smooth 10',
    '#EXTINF:120,Carlo Serafini - SopranoRibbonSax',
    'SopranoRibbonSax',
    '#EXTINF:310,Carlo Serafini - summer 2006 in 11 limit',
    'summer 2006 in 11 limit',
    '#EXTINF:331,Carlo Serafini -  Sunday Mourning',
    'Sunday Mourning',
    '#EXTINF:256,Carlo Serafini - The 88th Door',
    'The 88th Door',
    '#EXTINF:272,Carlo Serafini - The Singing Alchemist',
    'The Singing Alchemist',
    '#EXTINF:221,Carlo Serafini - Thirteenstan',
    'Thirteenstan',
    '#EXTINF:166,Carlo Serafini - tiBETAn dreams',
    'tiBETAn dreams',
    '#EXTINF:161,Carlo Serafini - Tim\'s Flutes',
    'Tim\'s Flutes',
    '#EXTINF:204,Carlo Serafini - Tribalism #1',
    'Tribalism #1',
    '#EXTINF:193,Carlo Serafini - Tribalism #2',
    'Tribalism #2',
    '#EXTINF:138,Carlo Serafini - twoatonce',
    'twoatonce',
    '#EXTINF:134,Carlo Serafini - Two At Once 2',
    'Two At Once 2',
    '#EXTINF:510,Carlo Serafini - Underwater Dreaming',
    'Underwater Dreaming',
    '#EXTINF:311,Carlo Serafini - Venusian Wedding Band',
    'Venusian Wedding Band',
    '#EXTINF:349,Carlo Serafini - Vimantra',
    'Vimantra',
    '#EXTINF:480,Carlo Serafini - Vocodrone',
    'Vocodrone',
    '#EXTINF:269,Carlo Serafini - Waltz10',
    'Waltz10',
    '#EXTINF:412,Carlo Serafini -  WhirliZen',
    'WhirliZen',
    '#EXTINF:72,Carlo Serafini - Wyshnegradsky\'s neutral vocoder',
    'Wyshnegradsky\'s neutral vocoder',
    '#EXTINF:247,Carlo Serafini - Xenharmonic Liberation Army',
    'Xenharmonic Liberation Army',
    '#EXTINF:217,Carlo Serafini - Zawigam',
    'Zawigam',
];


console.log(premp3.filter(track =>  track.indexOf('#EXTINF') ==-1).join('<br/>'))