[functions]
  directory = "functions"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/"
  to = "/.netlify/functions/home"
  status = 200
[[redirects]]
  from = "/list.json"
  to = "/.netlify/functions/list"
  status = 200